dataset: NCI1
aug: baseline
model_type: transformer
graph_pooling: cls

seed: 12344
batch_size: 128
lr: 0.0001
scheduler: cosine

num_encoder_layers: 4
runs: 5

d_model: 256
gnn_emb_dim: 256

transformer_dropout: 0.1

epochs: 100

data_tmp: "/data/adnans/tmp"
data_root: "/data/adnans/ogb"
nhead: 8
gnn_virtual_node: true