dataset: ogbg-molhiv
aug: baseline
model_type: gnn
gnn_type: gin
gnn_virtual_node: true
runs: 5
seed: 12344
batch_size: 256
eval_batch_size: 1024
lr: 0.001
start-eval: 1
scheduler: plateau


wandb_run_idx: baseline_0001