dataset: ogbg-code2
aug: baseline
model_type: gnn-bert

checkpoint: bert-base-uncased
freeze_bert: 0
unfreeze_bert: 30
warmup_epochs: 30

gnn_type: gin
gnn_virtual_node: false

graph_pooling: cls

batch_size: 16
lr: 0.0001

runs: 1
seed: 2000

transformer_norm_input: true

d_model: 768
dim_feedforward: 256
num_encoder_layers: 4
scheduler: custom

transformer_dropout: 0.1
gnn_dropout: 0.1

data_root: "/data/ethanbmehta/ogb"
data_tmp: "/data/ethanbmehta/tmp"

