dataset: ogbg-code2
aug: baseline
model_type: gnn-transformer

gnn_type: gcn
gnn_virtual_node: true

graph_pooling: cls

batch_size: 16
lr: 0.0001

runs: 1
seed: 2000

transformer_norm_input: true

data_root: "/data/adnans/ogb"
data_tmp: "/data/adnans/tmp"
