dataset: ogbg-pcqm
aug: baseline
model_type: gnn-transformer
gnn_type: gsan
gnn_virtual_node: true
runs: 1

gnn_dropout: 0.5


scheduler: cosine
data_tmp: "/data/adnans/tmp"
data_root: "/data/adnans/ogb"
fill_value: 0.0
normalizer: tanh
feature_mlp: true
gnn_residual: true

warmup_epochs: 20
lr: 0.0002
epochs: 300
batch_size: 256
gnn_num_layer: 5
gnn_emb_dim: 256

graph_pooling: cls
transformer_norm_input: true