dataset: ogbg-pcqm
aug: baseline
model_type: appnp
gnn_type: gin++
gnn_virtual_node: true
runs: 1

gnn_dropout: 0.5


scheduler: cosine
data_tmp: "/data/adnans/tmp"
data_root: "/data/adnans/ogb"
fill_value: 0.0
normalizer: tanh
feature_mlp: true
gnn_residual: true

warmup_epochs: 20
lr: 0.00025
epochs: 400
batch_size: 128
gnn_num_layer: 10
gnn_emb_dim: 384
graph_pooling: "mean"
gnn_JK: "last"