dataset: NCI1
aug: baseline
model_type: gnn-bert

checkpoint: "bert-base-uncased"
freeze_bert: True

gnn_type: gin
gnn_virtual_node: false

graph_pooling: cls

lr: 0.000005

seed: 12344

transformer_norm_input: true

runs: 1
epochs: 100

d_model: 768
dim_feedforward: 256
num_encoder_layers: 4
scheduler: cosine

transformer_dropout: 0.1
gnn_dropout: 0.1
