dataset: ogbg-molpcba
aug: baseline
model_type: gnn
gnn_type: gsan
gnn_virtual_node: true
runs: 1
batch_size: 256
gnn_dropout: 0.5
epochs: 100
lr: 0.001
scheduler: cosine
data_tmp: "/data/adnans/tmp"
data_root: "/data/adnans/ogb"
fill_value: 0
normalizer: softmax
feature_mlp: true
gnn_residual: true